### ISSUE TITLE
mention dependency on django-htmlmin

### ISSUE THREAD

**Issue by bbbart** [pietroalbini/lektor-minify-assets#2]
Hi!

Thank you for this plugin, it's really very helpful.

However, after installing it, it didn't work straight away for me. I kept on getting the error that `htmlmin.minify` couldn't be found. https://stackoverflow.com/questions/41113011/importerror-no-module-named-htmlmin-minify helped me in figuring out that django-htmlmin had to be installed as well.

Perhaps it's possible to list this as a dependency to get it automatically installed when adding this plugin to Lektor?

Thanks again for this plugin!

**Comment by emilyalbini** [comment]
Thanks for opening this issue.

I think [django_htmlmin is already marked as a dependency](https://github.com/pietroalbini/lektor-minify/blob/7a0d4ae08d894d04211eeb007082a3c55340b792/setup.py#L64)?

**Comment by bbbart** [comment]
Hm, yes, apparently it is. I installed it using `lektor plugins add lektor-htmlmin`, which resulted in a couple of packages to get installed at the next build, but django-htmlmin wasn't one of them.

Perhaps a lektor problem then?

Or I should have installed the plugin using pip and then manually added it to the `.lektorproject`-file?

**Comment by emilyalbini** [comment]
I just tested this with a fresh Lektor install and it seems to be installing fine. Can you try again?

By the way, it's `lektor plugins add lektor-minify`, not `lektor-htmlmin` ;-)
